### ISSUE TITLE
 Custom edge column names

### ISSUE THREAD

**Issue by xserve98** [facebookincubator/ent#394] opened 2020-03-19 09:16 UTC
If you can consider supporting edge of the custom field name?

**Comment by hantmac** [comment] 2020-03-19 09:30
> If you can consider supporting edge of the custom field name?

I can't get your point. For an example?

**Comment by xserve98** [comment] 2020-03-19 10:04
Sorry, my English is not very good.

A table exists with many edges, I want to customize their names
`edge.To("cars", Car.Type).StorageKey("cars_id")`

**Comment by a8m** [comment] 2020-03-19 10:05
Thanks for opening this issue, and thanks @hantmac for your collaboration.

Closing, since this is duplicate of #126. Please, let's continue the discussion there.

**Closed by a8m** 2020-03-19 10:05 UTC
