### ISSUE TITLE
Edges with UUID primary key

### ISSUE THREAD

**Issue by forestlovewood** [facebookincubator/ent#256] opened 2019-12-22 09:06 UTC
I'm trying to create schema objects to replicate an existing Postgres database which uses UUID primary keys and a M2M relationship between two large tables. I've found that when I create a UUID field, named `id`, attempting to build the project results in errors.

Profile schema:

```
// Fields of the Profile.
func (Profile) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}),
		field.UUID("uuid", uuid.UUID{}).Default(uuid.New),
		field.String("name"),
	}
}

// Edges of the Profile.
func (Profile) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("files", File.Type),
	}
}
```

File schema:

```
// Fields of the File.
func (File) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}),
		field.UUID("uuid", uuid.UUID{}).Default(uuid.New),
		field.String("name").Nillable().Optional(),
	}
}

// Edges of the File.
func (File) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("profiles", Profile.Type).Ref("files"),
	}
}
```

Error output:

```
pkg/testproject/database/file_update.go:184:17: cannot use eid (type uuid.UUID) as type int in append
pkg/testproject/database/file_update.go:187:44: cannot use ids (type []uuid.UUID) as type []int in argument to "github.com/facebookincubator/ent/dialect/sql".InInts
pkg/testproject/database/file_update.go:198:35: cannot use id (type uuid.UUID) as type int in array or slice literal
pkg/testproject/database/file_update.go:198:39: cannot use eid (type uuid.UUID) as type int in array or slice literal
pkg/testproject/database/file_update.go:386:17: cannot use eid (type uuid.UUID) as type int in append
pkg/testproject/database/file_update.go:389:44: cannot use ids (type []uuid.UUID) as type []int in argument to "github.com/facebookincubator/ent/dialect/sql".InInts
pkg/testproject/database/file_update.go:400:35: cannot use id (type uuid.UUID) as type int in array or slice literal
pkg/testproject/database/file_update.go:400:39: cannot use eid (type uuid.UUID) as type int in array or slice literal
pkg/testproject/database/profile_update.go:165:17: cannot use eid (type uuid.UUID) as type int in append
pkg/testproject/database/profile_update.go:168:44: cannot use ids (type []uuid.UUID) as type []int in argument to "github.com/facebookincubator/ent/dialect/sql".InInts
pkg/testproject/database/profile_update.go:168:44: too many errors
```

Is there a solution for this, or are UUID primary keys just not supported with edges?

**Comment by a8m** [comment] 2019-12-22 10:00
Hey @forestlovewood, and thanks for raising up this issue.

I'm aware about this limitation, and it's part of my effort to allow custom-id fields (see #127). 
We're working on refactoring some of the SQL storage layer, and after I finished that, this issue (and eager-loading) will be easier to fix. 

I'm closing this issue because it's duplicate of #127, but I'll update this issue once it's done.

**Closed by a8m** 2019-12-22 10:00 UTC
