### ISSUE TITLE
Incorrect handling of table names causes conflicts with Golang keywords

### ISSUE THREAD

**Issue by kallydev** [facebookincubator/ent#284] opened 2020-01-14 14:48 UTC
Hi, I found that the generated table names conflicted with Golang keywords when using ent.

When I use Package as the table name, try to generate code using ent.

```golang
type Package struct {}
```

```bash
$ entc generate ./ent/schema/

# The error message is too long, I deleted the path
format file /ent/package_create.go:277:10: expected operand, found 'package' (and 10 more errors)
```

You can see that the structure name is converted to lowercase in the `(t Type) Package() string` function. If I use the words `Package` or `Type` as the database table name, it will be converted to `package` or `type`, which will conflict with the Golang keywords.

https://github.com/facebookincubator/ent/blob/f270e41f6e45131c72a0c6d3991180a1091d7eb4/entc/gen/type.go#L216

Note the **fourth line** of code generated below, this will produce an error.

```golang
var (
	pa = &Package{config: pc.config}
	spec = &sqlgraph.CreateSpec{
		Table: package.Table,
		ID: &sqlgraph.FieldSpec{
			Type: field.TypeUUID,
			Column: package.FieldID,
		},
	}
)
```

I think it can be solved by using the following method like #276.

https://github.com/facebookincubator/ent/blob/f270e41f6e45131c72a0c6d3991180a1091d7eb4/entc/gen/type.go#L779-L784

Change the package name.

```golang
package package

package _package
```

And add the package alias.

```golang
import "github.com/username/repository/package"

import _package "github.com/username/repository/package"
```
I wanted to submit the PR after fixing it myself, but when I modified [import.tmpl](https://github.com/facebookincubator/ent/blob/master/entc/gen/template/import.tmpl), it didn't work and I didn't find the reason, so I gave up :)

**Comment by a8m** [comment] 2020-01-14 16:17
Hey @kallydev, and thanks for raising up this issue. 
This somehow similar to #280.

I think it's fine in both cases to reject these names in codegen (@alexsn is also agreeing with me here). 

If you want to create a PR, let me know (or I can take it).

**Comment by marwan-at-work** [comment] 2020-01-16 00:07
Not sure if this is related, but I also get build errors if the model is called `Spec` -- You can reproduce by going through the get started tutorial and doing `entc init Spec` instead of `User`.

**Comment by marwan-at-work** [comment] 2020-01-16 01:15
Dug a little more into it, seems to be a collision between a package import path and a declared variable called `spec`

**Comment by kallydev** [comment] 2020-01-16 05:45
> Not sure if this is related, but I also get build errors if the model is called `Spec` -- You can reproduce by going through the get started tutorial and doing `entc init Spec` instead of `entc init Spec`.

Thanks for your help. This problem seems to have nothing to do with ent initialization, but caused by ent generation.

> Dug a little more into it, seems to be a collision between a package import path and a declared variable called `spec`

Yes. table names are usually plural in `PostgreSQL`. If the structure name of ent is plural, this problem can be avoided temporarily. However, if the structure name is plural, it will conflict with the semantics of the array. ent may need to provide an override name for the table name.

**Comment by a8m** [comment] 2020-01-16 15:31
Reopen because there's more work to do for closing this one.

**Comment by a8m** [comment] 2020-03-06 05:54
Merging this issue to #374

Thanks!

**Closed by a8m** 2020-03-06 05:54 UTC
