### ISSUE TITLE
missing sqlite schema function

### ISSUE THREAD

**Issue by sohaha** [facebookincubator/ent#345] opened 2020-02-14 04:21 UTC
github.com/facebookincubator/ent@v0.1.1/dialect/sql/schema/sqlite.go:152
```
func (d *SQLite) table(context.Context, dialect.Tx, string) (*Table, error) { return nil, nil }
```

If the table already exists the situation will cause the program to panic.

![image](https://user-images.githubusercontent.com/18098083/74501256-85c63d80-4f24-11ea-8df6-c88ed1eeb5df.png)

**Comment by a8m** [comment] 2020-02-14 05:47
Thanks for reporting this issue. 

Closing since it’s a duplicate of #200, and there’s an ongoing PR for adding this support.

**Closed by a8m** 2020-02-14 05:47 UTC
