### ISSUE TITLE
Question: order based on edge

### ISSUE THREAD

**Issue by jd88** [facebookincubator/ent#227] opened 2019-12-10 10:29 UTC
I started using entgo for a new project and really like it so far. Nonetheless I can into a problem with respect to the order. So far entgo supports ordering based on fields, as the example shows:
`users, err := client.User.Query().
    Order(ent.Asc(user.FieldName)).
    All(ctx)`
Is it also possible to order based on edges? I unsuccessfully tried this approach:
`Query := storage.Db().Person.
	Query().
	Where(person.DeletedAtIsNil()).
	Offset(*offset).
	Limit(*limit).
	Clone()
`
`
if orderByFirstname != nil && *orderByFirstname == "asc" { Query=Query.QueryFirstname().Order(ent.Asc(stringvalue.FieldValue)).QueryFirstnameHolder().Clone()
}
`
Do you have suggestions on this issue?

**Comment by a8m** [comment] 2019-12-10 12:59
Hey @jd88, 
It doesn't support by the framework, because the relation properties reside in a different table (and a JOIN step is required here). 
However, I think you can add this logic by yourself with a custom order function.

**Comment by jd88** [comment] 2019-12-10 18:34
Hi @a8m Thank you for the swift response. I tried to look in to a starting point for that custom function. Do I use a predicate for this or do you suggest to query the relevant e.g. firstnames in order and then query to corresponding persons?

**Comment by a8m** [comment] 2019-12-10 18:47
If you can paste here your schema (`ent.Schema`) and the query your try to apply (in pseudo code), I'll try to help you with this.

Anyway, I'm closing this issue since it's not a bug. 
Thanks

**Closed by a8m** 2019-12-10 18:47 UTC
Labels: Question

**Comment by a8m** [comment] 2019-12-10 18:50
BTW, use triple back-ticks (```) for code blocks.

**Comment by jd88** [comment] 2019-12-10 18:56
Thank you four help!
Schema:
```
// Person holds the schema definition for the Person entity.
type Person struct {
	ent.Schema
}

// Fields of the Person.
func (Person) Fields() []ent.Field {
	return []ent.Field{
		field.Time("created_at").Default(time.Now),
		field.Time("deleted_at").Optional(),
		field.Time("birthday").Optional(),
	}
}

// Edges of the Person.
func (Person) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("firstname", StringValue.Type).Required(),
		edge.To("lastname", StringValue.Type).Required(),
	}
}
```

```
// StringValue holds the schema definition for the StringValue entity.
type StringValue struct {
	ent.Schema
}

// Fields of the StringValue.
func (StringValue) Fields() []ent.Field {
	return []ent.Field{
		field.String("value"),
		field.Time("created_at").
			Default(time.Now),
		field.Time("updated_at").
			Optional(),
		field.Time("valid_from").
			Default(time.Now),
		field.Time("valid_until").
			Optional(),
	}
}

// Edges of the StringValue.
func (StringValue) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("firstnameHolder", Person.Type).
		Ref("firstname").
		Unique(),
		edge.From("lastnameHolder", Person.Type).
		Ref("lastname").
		Unique(),
	}
}
```
Firstname and lastname are possibly not the best example, however still they are subject to change. I wanted to be able to track these changes. But also I want to query the person ordered by firstname or lastname... The StringValue field holds any value that is a string and that is subject to change... that was the idea. May there is also an easier way to realize this?
