### ISSUE TITLE
Add date type 

### ISSUE THREAD

**Issue by danf0rth** [facebookincubator/ent#305] opened 2020-01-21 17:31 UTC
Hi! :)

It is not always necessary to store value in timestamp. Sometimes the resolution of MySQL/Postgres `date` type is enough, for example to store users birthdays.

I am currently working to add such support [here](https://github.com/danf0rth/ent/tree/date-type).
Not sure that i can add a Gremlin and SQLite dialect support, because i am not familiar with them. 

Is there are any reasons why there is still no support of date type? Maybe i missed some switch that stores date without too much precision?

Thanks!

**Comment by a8m** [comment] 2020-01-21 19:59
Hey @danf0rth, I think this is a duplicate of https://github.com/facebookincubator/ent/issues/277, and we can move the conversation to there, and as I commented there:

> We should allow users to choose the dialect type they want, and this should be addressed.

**Closed by a8m** 2020-01-21 19:59 UTC
